name: cod_barras
description: App de inventario con lectura de código de barras/QR
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  #Uso de base de datos local
  sqflite: ^2.3.0
  path: ^1.9.0

  #Pare el manejo de estados
  provider: ^6.1.1

  #Para el escaneo de códigos de barras o de QRs con la cámara
  mobile_scanner: ^5.1.1

  #Para manejar el formateo de fechas
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
